# Generated by Django 4.0.4 on 2022-06-08 11:37

import blog_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(validators=[blog_module.models.validate_rating]),
        ),
    ]
