# Generated by Django 4.0.4 on 2022-06-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0004_post_image_alter_post_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
