# Generated by Django 4.0.6 on 2022-07-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
