# Generated by Django 4.0.6 on 2022-07-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0006_post_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20)),
                ('is_active', models.BooleanField(verbose_name='active')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='post_tags', to='blog_module.posttag', verbose_name='Post tags'),
        ),
    ]
