# Generated by Django 4.0.6 on 2022-07-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0007_posttag_alter_post_is_active_post_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='is_active',
        ),
        migrations.AddField(
            model_name='posttag',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='blog_module.post'),
        ),
    ]
