# Generated by Django 4.0.6 on 2022-07-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0008_alter_posttag_options_remove_post_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttag',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='post_tags', to='blog_module.posttag', verbose_name='Post tags'),
        ),
    ]
