# Generated by Django 4.0.6 on 2022-07-30 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0011_posttag_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttag',
            name='posts',
        ),
        migrations.AddField(
            model_name='posttag',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_module.post', verbose_name='Posts'),
        ),
    ]
