# Generated by Django 4.0.6 on 2022-07-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0012_remove_posttag_posts_posttag_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttag',
            name='posts',
        ),
    ]
