# Generated by Django 4.0.6 on 2022-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0013_remove_posttag_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvisit',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
