# Generated by Django 4.0.6 on 2022-08-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0014_postvisit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvisit',
            name='count',
        ),
    ]
