# Generated by Django 4.0.6 on 2022-08-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0015_remove_postvisit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='title')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='url title')),
                ('is_active', models.BooleanField(verbose_name='active')),
                ('is_delete', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='post_categories', to='blog_module.postcategory', verbose_name='categories'),
        ),
    ]
