# Generated by Django 4.0.6 on 2022-09-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0018_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='user',
        ),
    ]
