# Generated by Django 4.1.1 on 2022-10-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0021_alter_postcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
