# Generated by Django 4.1.1 on 2022-10-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0023_alter_postcomment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment',
            new_name='text',
        ),
    ]
