# Generated by Django 4.0.6 on 2022-07-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=models.ImageField(upload_to='wallpapers'),
        ),
    ]
